# Python Final Project

In [1]:
# importing packages
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Loading data
world_regions= pd.read_excel('WDIW_Dataset.xlsx') # index_col = 0) # index_col = 0 uses Country Code as index.

# Filtering Data
Africa_dataset = world_regions[world_regions['Cool Name'] == 'Jazz' ]

### africa.loc[["COG", ]] code for row Access by .loc (label-based)
#### africa.iloc[[2]] #code for  row Access by .iloc (index-based)

# Head Analysis
Africa_dataset.head()

,Country Code,Country Name,Hult Region,Cool Name,Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)","Adolescent fertility rate (births per 1,000 women ages 15-19)",Age dependency ratio (% of working-age population),"Age dependency ratio, old (% of working-age population)",...,Poverty headcount ratio at national poverty lines (% of population),"Prevalence of HIV, total (% of population ages 15-49)",Prevalence of undernourishment (% of population),"Prevalence of underweight, weight for age (% of children under 5)",Rural population (% of total population),"Services, value added (% of GDP)",Surface area (sq. km),Tax revenue (% of GDP),Urban population (% of total population),Urban population growth (annual %)
25,BWA,Botswana,East/South Africa,Jazz,62.824947,24.264212,80.393379,46.061,62.669557,6.648038,...,NaN,20.7,26.4,NaN,31.300,59.112989,581730.0,22.144134,68.700,3.193041
31,BDI,Burundi,East/South Africa,Jazz,9.300000,1.658409,61.800000,55.590,91.359181,4.184565,...,NaN,1.1,NaN,NaN,87.294,NaN,27830.0,NaN,12.706,5.716012
44,COG,"Congo, Repub. of the",East/South Africa,Jazz,66.214851,24.180856,87.428864,112.229,80.464234,4.769957,...,NaN,2.7,40.3,NaN,33.541,40.079352,342000.0,NaN,66.459,3.262154
53,DJI,Djibouti,East/South Africa,Jazz,60.200000,26.294945,69.960000,18.841,52.528580,6.797487,...,21.1,1.2,18.9,NaN,22.352,71.886722,23200.0,NaN,77.648,1.754559
61,ERI,Eritrea,East/South Africa,Jazz,48.423790,30.188929,76.504364,52.553,NaN,NaN,...,NaN,0.7,NaN,NaN,NaN,NaN,117600.0,NaN,NaN,NaN

In [2]:
# Val = Values

# Number of missing values

# Number of null values aggregated
null_val = Africa_dataset.isnull().agg('sum').sort_values(ascending = False)

# defining missing values
missing_val = null_val[null_val > 0]

# Display the missing values
print(missing_val)

Educational attainment, at least Bachelor's or equivalent, population 25+, total (%) (cumulative)          22
Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative)                     22
Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative)         22
Prevalence of underweight, weight for age (% of children under 5)                                          22
Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative)    22
Literacy rate, adult total (% of people ages 15 and above)                                                 22
Literacy rate, youth total (% of people ages 15-24)                                                        22
Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative)           22
Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative)          22
Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)         22
Educational attainment, at least Master's or equivalent, population 25+, total (%) (cumulative)            22
GINI index (World Bank estimate)                                                                           21
Income share held by fourth 20%                                                                            21
Income share held by lowest 20%                                                                            21
Income share held by second 20%                                                                            21
Income share held by third 20%                                                                             21
Income share held by highest 20%                                                                           21
Poverty headcount ratio at $3.20 a day (2011 PPP) (% of population)                                        21
Poverty headcount ratio at $1.90 a day (2011 PPP) (% of population)                                        21
Births attended by skilled health staff (% of total)                                                       21
Poverty headcount ratio at national poverty lines (% of population)                                        18
Government expenditure on education, total (% of government expenditure)                                   15
Tax revenue (% of GDP)                                                                                      6
Services, value added (% of GDP)                                                                            4
Prevalence of undernourishment (% of population)                                                            4
Industry (including construction), value added (% of GDP)                                                   4
Population in the largest city (% of urban population)                                                      4
Agriculture, forestry, and fishing, value added (% of GDP)                                                  4
Merchandise trade (% of GDP)                                                                                3
Military expenditure (% of GDP)                                                                             3
GDP growth (annual %)                                                                                       3
Population density (people per sq. km of land area)                                                         2
GDP (current US$)                                                                                           2
Age dependency ratio, old (% of working-age population)                                                     1
Age dependency ratio, young (% of working-age population)                                                   1
Age dependency ratio (% of working-age population)                                                          1
Access to electricity, rural (% of rural population)                                                        1
Armed forces personnel (% of total labor force)                                                             1
Urban population growth (annual %)                                                                          1
Population ages 15-64 (% of total population)                                                               1
Population ages 0-14 (% of total population)                                                                1
Population, male                                                                                            1
Population, female                                                                                          1
Rural population (% of total population)                                                                    1
Population growth (annual %)                                                                                1
Population ages 65 and above (% of total population)                                                        1
Population, total                                                                                           1
Surface area (sq. km)                                                                                       1
Urban population (% of total population)                                                                    1
dtype: int64

## Missing Values
### Finding Values
#### Test set

In [3]:
# Africa

Africa = ['BWA','BDI','COG','DJI','ERI', 'SWZ','ETH','KEN','LSO','MDG', 
          'MWI','MOZ','NAM','RWA','SOM','ZAF','SSD','TZA','TGO','UGA', 
         'ZMB','ZWE']

# Subset of Countr - dies
AfricaDf = Africa_dataset[Africa_dataset['Country Code'].isin(Africa)]

In [5]:

# Checking missing values for Africa Data Set
AfricaT = AfricaDf.transpose()

AfricaT.columns = Africa

# mv = missing values

Africa_mv_sorted = (AfricaT.isnull().sum().sort_values(ascending = False) / len(AfricaT)) * 100

Africa_mv_sorted

ERI    68.656716
SSD    46.268657
SOM    43.283582
BDI    37.313433
SWZ    35.820896
BWA    34.328358
COG    34.328358
MDG    34.328358
ETH    32.835821
TGO    32.835821
TZA    32.835821
NAM    32.835821
MOZ    32.835821
ZMB    32.835821
LSO    32.835821
ZWE    31.343284
KEN    31.343284
RWA    31.343284
ZAF    31.343284
UGA    31.343284
MWI    31.343284
DJI    22.388060
dtype: float64

In [13]:
# Checking missing values per Column
# mc = Missing Cols
Africa_mc = AfricaDf.isnull().sum().sort_values(ascending = False)

# 68 indicators
print(f'Matrix Shape: {AfricaDf.shape}') 

# Indicators with 100% missing values (22 Missing Values)
print(Africa_mc[Africa_mc == 22])

Matrix Shape: (22, 67)
Educational attainment, at least Bachelor's or equivalent, population 25+, total (%) (cumulative)          22
Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative)                     22
Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative)         22
Prevalence of underweight, weight for age (% of children under 5)                                          22
Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative)    22
Literacy rate, adult total (% of people ages 15 and above)                                                 22
Literacy rate, youth total (% of people ages 15-24)                                                        22
Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative)           22
Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative)          22
Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)         22
Educational attainment, at least Master's or equivalent, population 25+, total (%) (cumulative)            22
dtype: int64

In [18]:
# Indicators between 1 to 3 missing datapoints

Africa_mc[Africa_mc <= 3][Africa_mc > 0]

Merchandise trade (% of GDP)                                 3
Military expenditure (% of GDP)                              3
GDP growth (annual %)                                        3
Population density (people per sq. km of land area)          2
GDP (current US$)                                            2
Age dependency ratio, old (% of working-age population)      1
Age dependency ratio, young (% of working-age population)    1
Age dependency ratio (% of working-age population)           1
Access to electricity, rural (% of rural population)         1
Armed forces personnel (% of total labor force)              1
Urban population growth (annual %)                           1
Population ages 15-64 (% of total population)                1
Population ages 0-14 (% of total population)                 1
Population, male                                             1
Population, female                                           1
Rural population (% of total population)                     1
Population growth (annual %)                                 1
Population ages 65 and above (% of total population)         1
Population, total                                            1
Surface area (sq. km)                                        1
Urban population (% of total population)                     1
dtype: int64

In [19]:
# Only one missing value
Africa_mc[Africa_mc >= 1 ][Africa_mc < 2]

Age dependency ratio, old (% of working-age population)      1
Age dependency ratio, young (% of working-age population)    1
Age dependency ratio (% of working-age population)           1
Access to electricity, rural (% of rural population)         1
Armed forces personnel (% of total labor force)              1
Urban population growth (annual %)                           1
Population ages 15-64 (% of total population)                1
Population ages 0-14 (% of total population)                 1
Population, male                                             1
Population, female                                           1
Rural population (% of total population)                     1
Population growth (annual %)                                 1
Population ages 65 and above (% of total population)         1
Population, total                                            1
Surface area (sq. km)                                        1
Urban population (% of total population)                     1
dtype: int64

In [20]:
# Subset indicators with at least 1 missing value. This is a boolean DataFrame
# mb = missing boolean
Africa_mb = AfricaDf[Africa_mc[Africa_mc >= 1].index].isnull().copy()


AfricaMissingbyCountry = AfricaDf[Africa_mb.columns.copy()]

# Created Country code column in order to add it as an index
AfricaMissingbyCountry.loc[:,'CountryCode'] = AfricaDf['Country Code'].copy()

# modified index to have the country code. Easier subsetting!
AfricaMissingbyCountry = AfricaMissingbyCountry.set_index('CountryCode').copy()

# The final dataframe contains the dataframe that has missing values 
AfricaMissingbyCountry

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:376: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

,"Educational attainment, at least Bachelor's or equivalent, population 25+, total (%) (cumulative)","Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative)","Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative)","Prevalence of underweight, weight for age (% of children under 5)","Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative)","Literacy rate, adult total (% of people ages 15 and above)","Literacy rate, youth total (% of people ages 15-24)","Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative)","Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative)","Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)",...,Population ages 15-64 (% of total population),Population ages 0-14 (% of total population),"Population, male","Population, female",Rural population (% of total population),Population growth (annual %),Population ages 65 and above (% of total population),"Population, total",Surface area (sq. km),Urban population (% of total population)
CountryCode,,,,,,,,,,,,,,,,,,,,,
BWA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,61.474323,34.438841,1062494.0,1142634.0,31.300,2.070326,4.086836,2205128.0,581730.0,68.700
BDI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,52.257745,45.555494,5365503.0,5461521.0,87.294,3.181368,2.186761,10827024.0,27830.0,12.706
COG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,55.412640,41.944197,2551316.0,2559386.0,33.541,2.570630,2.643163,5110702.0,342000.0,66.459
DJI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.561451,29.982025,497395.0,446702.0,22.352,1.599962,4.456524,944097.0,23200.0,77.648
ERI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117600.0,NaN
SWZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,57.647681,38.344424,547251.0,577502.0,76.375,0.962068,4.007895,1124753.0,17360.0,23.625
ETH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,55.261371,41.250798,53214774.0,53185250.0,79.690,2.663468,3.487830,106400024.0,1104300.0,20.310
KEN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,57.393882,40.350012,24950304.0,25271169.0,73.438,2.356813,2.256106,50221473.0,580370.0,26.562
LSO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,62.145966,32.981391,1030103.0,1061309.0,72.270,0.787780,4.872644,2091412.0,30360.0,27.730
MDG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56.097504,40.972312,12751864.0,12818676.0,63.478,2.679883,2.930184,25570540.0,587295.0,36.522
MWI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53.054109,44.296877,8709591.0,8960669.0,83.286,2.666616,2.649014,17670260.0,118480.0,16.714
MOZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,52.142206,44.959461,13891296.0,14757711.0,64.545,2.900629,2.898333,28649007.0,786380.0,35.455
NAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,59.448572,36.882537,1163617.0,1238986.0,50.995,1.872154,3.668892,2402603.0,824290.0,49.005
RWA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,57.014108,40.136129,5886052.0,6094885.0,82.875,2.639665,2.849763,11980937.0,26340.0,17.125
SOM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,50.393336,46.752980,7275835.0,7313284.0,55.609,2.804769,2.853684,14589119.0,637660.0,44.391
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.630562,29.150260,28116850.0,28883601.0,34.150,1.407741,5.219179,57000451.0,1219090.0,65.850
SSD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,54.527406,42.056830,5459485.0,5451274.0,80.654,0.719738,3.415765,10910759.0,NaN,19.346
TZA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53.099890,44.316449,27296698.0,27367208.0,66.947,2.995388,2.583661,54663906.0,947300.0,33.053
TGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,55.512196,41.637576,3827461.0,3871014.0,58.838,2.479318,2.850227,7698475.0,56790.0,41.162
UGA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,50.759757,47.319938,20246144.0,20916321.0,76.804,3.749875,1.920305,41162465.0,241550.0,23.196
ZMB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,52.503824,45.411369,8342800.0,8510888.0,57.024,2.951583,2.084807,16853688.0,752610.0,42.976
ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,54.505941,42.597868,6777124.0,7459621.0,67.763,1.460061,2.896191,14236745.0,390760.0,32.237

## Web Scraping (Test)

In [21]:
#UNCOMMENT (!PIP INSTALL) BEFORE RUNNING THIS CODE AND THEN COMMENT BACK AGAIN TO SPEED THE PROCESS
#!pip install world_bank_data --upgrade 

import world_bank_data as wb

# It's necessary to get the indicators code, this is different from the column names. 
    # E.g: Income share held by fourth 20% is coded as: SI.DST.04TH.20
    
missingIndicators = Africa_mc[Africa_mc >= 1].index.copy()

# Created empty dataframe with the column format that the API will return
    # We just need to append in a simple loop
indicatorsCodedMissing = pd.DataFrame(columns = ['name', 'unit', 'source', 'sourceNote', 'sourceOrganization', 'topics'])

# Loop to get the missing indicators and store the in the indicatorsCodedMissing data frame
for i in list(missingIndicators):
    indicatorsCodedMissing = indicatorsCodedMissing.append(wb.search_indicators(i))

# view the first the indicator names
print(f'{indicatorsCodedMissing.index[0:3]} \n')

indicatorsCodedMissing.head()

Index(['SI.DST.04TH.20', 'SI.DST.FRST.20', 'SI.DST.02ND.20'], dtype='object')

,name,unit,source,sourceNote,sourceOrganization,topics
SI.DST.04TH.20,Income share held by fourth 20%,,World Development Indicators,Percentage share of income or consumption is t...,"World Bank, Development Research Group. Data a...",Poverty
SI.DST.FRST.20,Income share held by lowest 20%,,World Development Indicators,Percentage share of income or consumption is t...,"World Bank, Development Research Group. Data a...","Poverty ,Aid Effectiveness"
SI.DST.02ND.20,Income share held by second 20%,,World Development Indicators,Percentage share of income or consumption is t...,"World Bank, Development Research Group. Data a...",Poverty
SI.DST.03RD.20,Income share held by third 20%,,World Development Indicators,Percentage share of income or consumption is t...,"World Bank, Development Research Group. Data a...",Poverty
SI.DST.05TH.20,Income share held by highest 20%,,World Development Indicators,Percentage share of income or consumption is t...,"World Bank, Development Research Group. Data a...",Poverty

In [22]:
# Now we obtain the data for the specific countries that we need

#UNCOMMENT (!PIP INSTALL) BEFORE RUNNING THIS CODE AND THEN COMMENT BACK AGAIN TO SPEED THE PROCESS 
#!pip install wbdata

import wbdata
from datetime import datetime

# missingIndicators = AfricaheadMissingCols[AfricaheadMissingCols > 1] 

# The indicators argument of get_dataframe needs to be a dictionary with 
    # the codes (previous step) as the key and the new column names as the values (missing Indicators)
    # It will return the Data frame with all the years in the world bank 
    
keys = list(indicatorsCodedMissing.index)
values = list(missingIndicators) 

wbQueriedAfrica = wbdata.get_dataframe(indicators = dict(zip(keys,values)), country = Africa, convert_date = False)

wbQueriedAfrica.head()

               Educational attainment, at least Bachelor's or equivalent, population 25+, total (%) (cumulative)  \
country  date
Botswana 1960                                                NaN
         1961                                                NaN
         1962                                                NaN
         1963                                                NaN
         1964                                                NaN

               Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative)  \
country  date
Botswana 1960                                                NaN
         1961                                                NaN
         1962                                                NaN
         1963                                                NaN
         1964                                                NaN

               Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative)  \
country  date
Botswana 1960                                                NaN
         1961                                                NaN
         1962                                                NaN
         1963                                                NaN
         1964                                                NaN

               Prevalence of underweight, weight for age (% of children under 5)  \
country  date
Botswana 1960                                                NaN
         1961                                                NaN
         1962                                                NaN
         1963                                                NaN
         1964                                                NaN

               Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative)  \
country  date
Botswana 1960                                                NaN
         1961                                                NaN
         1962                                                NaN
         1963                                                NaN
         1964                                                NaN

               Literacy rate, adult total (% of people ages 15 and above)  \
country  date
Botswana 1960                                             9963.0
         1961                                            10090.0
         1962                                            10420.0
         1963                                            10877.0
         1964                                            11346.0

               Literacy rate, youth total (% of people ages 15-24)  \
country  date
Botswana 1960                                             9940.0
         1961                                             9848.0
         1962                                            10335.0
         1963                                            10620.0
         1964                                            10916.0

               Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative)  \
country  date
Botswana 1960                                             9768.0
         1961                                             9754.0
         1962                                             9735.0
         1963                                            10311.0
         1964                                            10493.0

               Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative)  \
country  date
Botswana 1960                                             9470.0
         1961                                             9544.0
         1962                                             9570.0
         1963                                             9622.0
         1964                                            10074.0

               Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)  \
country  date
Botswana 1960                                             9069.0
         1961                                             9236.0
         1962                                             9322.0
         1963                                             9385.0
         1964                                             9510.0

               ...  Population ages 15-64 (% of total population)  \
country  date  ...
Botswana 1960  ...                                         9647.0
         1961  ...                                         9607.0
         1962  ...                                         9561.0
         1963  ...                                        10146.0
         1964  ...                                        10320.0

               Population ages 0-14 (% of total population)  Population, male  \
country  date
Botswana 1960                                           NaN            9382.0
         1961                                           NaN            9434.0
         1962                                           NaN            9434.0
         1963                                           NaN            9465.0
         1964                                           NaN            9929.0

               Population, female  Rural population (% of total population)  \
country  date
Botswana 1960                 NaN                                    9008.0
         1961                 NaN                                    9157.0
         1962                 NaN                                    9220.0
         1963                 NaN                                    9262.0
         1964                 NaN                                    9380.0

               Population growth (annual %)  \
country  date
Botswana 1960                           NaN
         1961                           NaN
         1962                           NaN
         1963                           NaN
         1964                           NaN

               Population ages 65 and above (% of total population)  \
country  date
Botswana 1960                                             8547.0
         1961                                             8793.0
         1962                                             8929.0
         1963                                             9006.0
         1964                                             9101.0

               Population, total  Surface area (sq. km)  \
country  date
Botswana 1960                NaN                 8022.0
         1961                NaN                 8364.0
         1962                NaN                 8575.0
         1963                NaN                 8703.0
         1964                NaN                 8803.0

               Urban population (% of total population)
country  date
Botswana 1960                                       NaN
         1961                                       NaN
         1962                                       NaN
         1963                                       NaN
         1964                                       NaN

[5 rows x 49 columns]

In [24]:
# Now we subset for a particular year

wbQueriedAfrica.sort_index(inplace=True)

# What is the total of missing values that there are per year 
for i in range(2013,2019,1):
    print('{} missing values out of {} for year {} '.format(wbQueriedAfrica.xs(str(i),level='date'). 
                                                            transpose().isnull().sum().sum(), # Calculates overall sum of null values
                                                            wbQueriedAfrica.shape[1] * len(wbQueriedAfrica.index.levels[0]), # Number of columns * number of countries = total possible missing values 
                                                            i) # ith year 
        )

# It seems that 2015 is the most non-missing updated info that we can obtain 

# data for 2015 is queried
wbQueriedAfrica2015 = wbQueriedAfrica.xs('2015',level='date')

# Printing the data frame to know the contents
wbQueriedAfrica2015

# saving it to excel
   
wbQueriedAfrica2015.to_excel('worldBank2015AfricaCountries.xlsx')  # This is commented so I don't overwrite by mistake the file

181 missing values out of 1078 for year 2013
333 missing values out of 1078 for year 2014
124 missing values out of 1078 for year 2015
328 missing values out of 1078 for year 2016
338 missing values out of 1078 for year 2017
343 missing values out of 1078 for year 2018