# Python Final Project

In [56]:
# importing packages
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Loading data
world_regions= pd.read_excel('WDIW_FDataset.xlsx') # index_col = 0) # index_col = 0 uses Country Code as index.

# Filtering Data
Africa_dataset = world_regions[world_regions['Cool Name'] == 'Jazz' ]

#### Africa_dataset.loc[:,["GDP (current US$)"]]  # code for row Access by .loc (label-based)

# Head Analysis

Africa_dataset.head()

,Country Code,Country Name,Hult Region,Cool Name,Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)","Adolescent fertility rate (births per 1,000 women ages 15-19)",Age dependency ratio (% of working-age population),"Age dependency ratio, old (% of working-age population)",...,Poverty headcount ratio at national poverty lines (% of population),"Prevalence of HIV, total (% of population ages 15-49)",Prevalence of undernourishment (% of population),"Prevalence of underweight, weight for age (% of children under 5)",Rural population (% of total population),"Services, value added (% of GDP)",Surface area (sq. km),Tax revenue (% of GDP),Urban population (% of total population),Urban population growth (annual %)
25,BWA,Botswana,East/South Africa,Jazz,62.824947,24.264212,80.393379,46.061,62.669557,6.648038,...,NaN,20.7,26.4,NaN,31.300,59.112989,581730.0,22.144134,68.700,3.193041
31,BDI,Burundi,East/South Africa,Jazz,9.300000,1.658409,61.800000,55.590,91.359181,4.184565,...,NaN,1.1,NaN,NaN,87.294,NaN,27830.0,NaN,12.706,5.716012
44,COG,"Congo, Repub. of the",East/South Africa,Jazz,66.214851,24.180856,87.428864,112.229,80.464234,4.769957,...,NaN,2.7,40.3,NaN,33.541,40.079352,342000.0,NaN,66.459,3.262154
53,DJI,Djibouti,East/South Africa,Jazz,60.200000,26.294945,69.960000,18.841,52.528580,6.797487,...,21.1,1.2,18.9,NaN,22.352,71.886722,23200.0,NaN,77.648,1.754559
61,ERI,Eritrea,East/South Africa,Jazz,48.423790,30.188929,76.504364,52.553,NaN,NaN,...,NaN,0.7,NaN,NaN,NaN,NaN,117600.0,NaN,NaN,NaN

In [57]:
# Val = Values

# Number of missing values

# Number of null values aggregated
null_val = Africa_dataset.isnull().agg('sum').sort_values(ascending = False)

# defining missing values
missing_val = null_val[null_val > 0]

# Display the missing values
print(missing_val)

Educational attainment, at least Master's or equivalent, population 25+, total (%) (cumulative)            21
Literacy rate, youth total (% of people ages 15-24)                                                        21
Educational attainment, at least Bachelor's or equivalent, population 25+, total (%) (cumulative)          21
Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative)         21
Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative)                     21
Prevalence of underweight, weight for age (% of children under 5)                                          21
Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative)          21
Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative)    21
Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)         21
Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative)           21
Literacy rate, adult total (% of people ages 15 and above)                                                 21
GINI index (World Bank estimate)                                                                           20
Births attended by skilled health staff (% of total)                                                       20
Income share held by highest 20%                                                                           20
Poverty headcount ratio at $1.90 a day (2011 PPP) (% of population)                                        20
Income share held by third 20%                                                                             20
Income share held by second 20%                                                                            20
Income share held by lowest 20%                                                                            20
Income share held by fourth 20%                                                                            20
Poverty headcount ratio at $3.20 a day (2011 PPP) (% of population)                                        20
Poverty headcount ratio at national poverty lines (% of population)                                        17
Government expenditure on education, total (% of government expenditure)                                   14
Tax revenue (% of GDP)                                                                                      6
Population in the largest city (% of urban population)                                                      4
Agriculture, forestry, and fishing, value added (% of GDP)                                                  4
Industry (including construction), value added (% of GDP)                                                   4
Prevalence of undernourishment (% of population)                                                            4
Services, value added (% of GDP)                                                                            4
Military expenditure (% of GDP)                                                                             3
Merchandise trade (% of GDP)                                                                                3
Population density (people per sq. km of land area)                                                         2
Armed forces personnel (% of total labor force)                                                             1
Age dependency ratio, young (% of working-age population)                                                   1
Age dependency ratio, old (% of working-age population)                                                     1
Age dependency ratio (% of working-age population)                                                          1
Access to electricity, rural (% of rural population)                                                        1
Urban population growth (annual %)                                                                          1
Population, female                                                                                          1
Population ages 15-64 (% of total population)                                                               1
Population, total                                                                                           1
Rural population (% of total population)                                                                    1
Population growth (annual %)                                                                                1
Urban population (% of total population)                                                                    1
Surface area (sq. km)                                                                                       1
Population ages 65 and above (% of total population)                                                        1
Population, male                                                                                            1
Population ages 0-14 (% of total population)                                                                1
dtype: int64

## Missing Values
### Finding Values
#### Test set

In [55]:
# Africa

Africa = ['BWA','BDI','COG','DJI','ERI', 'SWZ','ETH','KEN','LSO','MDG', 
          'MWI','MOZ','NAM','RWA','SOM','ZAF','SSD','TZA','UGA','ZMB',
          'ZWE']

# Subset of Countr - dies
AfricaDf = Africa_dataset[Africa_dataset['Country Code'].isin(Africa)]

AfricaDf.rename(columns={"Employment in agriculture (% of total employment) (modeled ILO estimate)"
                         : "Emp_agriculture","Employment in industry (% of total employment) (modeled ILO estimate)"
                         : "Emp_industry","Employment in services (% of total employment) (modeled ILO estimate)"
                         : "Emp_services","GDP (current US$)":"GDP_USD","GDP growth (annual %)":"GDP_growth"}, inplace=True)

AfricaDf.loc[:,["Emp_agriculture"]]

     Emp_agriculture
25         23.174000
31         91.860001
44         35.992001
53         50.405998
61         62.861000
63         13.109000
64         67.074997
101        57.834000
111        67.147003
119        68.425003
120        72.066002
135        71.920998
138        19.905001
162        67.080002
179        72.483002
180         5.222000
181        48.935001
191        66.924004
200        71.070000
214        54.191002
215        67.072998

In [38]:

# Checking missing values for Africa Data Set
AfricaT = AfricaDf.transpose()

AfricaT.columns = Africa

# mv = missing values

Africa_mv_sorted = (AfricaT.isnull().sum().sort_values(ascending = False) / len(AfricaT)) * 100

Africa_mv_sorted

ERI    65.671642
SSD    43.283582
SOM    41.791045
BDI    37.313433
SWZ    35.820896
BWA    34.328358
COG    34.328358
MDG    34.328358
ETH    32.835821
TZA    32.835821
NAM    32.835821
MOZ    32.835821
ZMB    32.835821
LSO    32.835821
ZWE    31.343284
KEN    31.343284
RWA    31.343284
ZAF    31.343284
UGA    31.343284
MWI    31.343284
DJI    22.388060
dtype: float64

In [39]:
# Checking missing values per Column
# mc = Missing Cols
Africa_mc = AfricaDf.isnull().sum().sort_values(ascending = False)

# 68 indicators
print(f'Matrix Shape: {AfricaDf.shape}') 

# Indicators with 100% missing values (22 Missing Values)
print(Africa_mc[Africa_mc == 22])

Matrix Shape: (21, 67)
Series([], dtype: int64)

In [40]:
# Indicators between 1 to 3 missing datapoints

Africa_mc[Africa_mc <= 3][Africa_mc > 0]

Military expenditure (% of GDP)                              3
Merchandise trade (% of GDP)                                 3
Population density (people per sq. km of land area)          2
Armed forces personnel (% of total labor force)              1
Age dependency ratio, young (% of working-age population)    1
Age dependency ratio, old (% of working-age population)      1
Age dependency ratio (% of working-age population)           1
Access to electricity, rural (% of rural population)         1
Urban population growth (annual %)                           1
Population, female                                           1
Population ages 15-64 (% of total population)                1
Population, total                                            1
Rural population (% of total population)                     1
Population growth (annual %)                                 1
Urban population (% of total population)                     1
Surface area (sq. km)                                        1
Population ages 65 and above (% of total population)         1
Population, male                                             1
Population ages 0-14 (% of total population)                 1
dtype: int64

In [41]:
# Only one missing value
Africa_mc[Africa_mc >= 1 ][Africa_mc < 2]

Armed forces personnel (% of total labor force)              1
Age dependency ratio, young (% of working-age population)    1
Age dependency ratio, old (% of working-age population)      1
Age dependency ratio (% of working-age population)           1
Access to electricity, rural (% of rural population)         1
Urban population growth (annual %)                           1
Population, female                                           1
Population ages 15-64 (% of total population)                1
Population, total                                            1
Rural population (% of total population)                     1
Population growth (annual %)                                 1
Urban population (% of total population)                     1
Surface area (sq. km)                                        1
Population ages 65 and above (% of total population)         1
Population, male                                             1
Population ages 0-14 (% of total population)                 1
dtype: int64

In [42]:
# Subset indicators with at least 1 missing value. This is a boolean DataFrame
# mb = missing boolean
Africa_mb = AfricaDf[Africa_mc[Africa_mc >= 1].index].isnull().copy()


AfricaMissingbyCountry = AfricaDf[Africa_mb.columns.copy()]

# Created Country code column in order to add it as an index
AfricaMissingbyCountry.loc[:,'CountryCode'] = AfricaDf['Country Code'].copy()

# modified index to have the country code. Easier subsetting!
AfricaMissingbyCountry = AfricaMissingbyCountry.set_index('CountryCode').copy()

# The final dataframe contains the dataframe that has missing values 
AfricaMissingbyCountry

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:376: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

,"Educational attainment, at least Master's or equivalent, population 25+, total (%) (cumulative)","Literacy rate, youth total (% of people ages 15-24)","Educational attainment, at least Bachelor's or equivalent, population 25+, total (%) (cumulative)","Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative)","Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative)","Prevalence of underweight, weight for age (% of children under 5)","Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative)","Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative)","Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)","Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative)",...,"Population, female",Population ages 15-64 (% of total population),"Population, total",Rural population (% of total population),Population growth (annual %),Urban population (% of total population),Surface area (sq. km),Population ages 65 and above (% of total population),"Population, male",Population ages 0-14 (% of total population)
CountryCode,,,,,,,,,,,,,,,,,,,,,
BWA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1142634.0,61.474323,2205128.0,31.300,2.070326,68.700,581730.0,4.086836,1062494.0,34.438841
BDI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5461521.0,52.257745,10827024.0,87.294,3.181368,12.706,27830.0,2.186761,5365503.0,45.555494
COG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2559386.0,55.412640,5110702.0,33.541,2.570630,66.459,342000.0,2.643163,2551316.0,41.944197
DJI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,446702.0,65.561451,944097.0,22.352,1.599962,77.648,23200.0,4.456524,497395.0,29.982025
ERI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,117600.0,NaN,NaN,NaN
SWZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,577502.0,57.647681,1124753.0,76.375,0.962068,23.625,17360.0,4.007895,547251.0,38.344424
ETH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53185250.0,55.261371,106400024.0,79.690,2.663468,20.310,1104300.0,3.487830,53214774.0,41.250798
KEN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25271169.0,57.393882,50221473.0,73.438,2.356813,26.562,580370.0,2.256106,24950304.0,40.350012
LSO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1061309.0,62.145966,2091412.0,72.270,0.787780,27.730,30360.0,4.872644,1030103.0,32.981391
MDG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12818676.0,56.097504,25570540.0,63.478,2.679883,36.522,587295.0,2.930184,12751864.0,40.972312
MWI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8960669.0,53.054109,17670260.0,83.286,2.666616,16.714,118480.0,2.649014,8709591.0,44.296877
MOZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14757711.0,52.142206,28649007.0,64.545,2.900629,35.455,786380.0,2.898333,13891296.0,44.959461
NAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1238986.0,59.448572,2402603.0,50.995,1.872154,49.005,824290.0,3.668892,1163617.0,36.882537
RWA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6094885.0,57.014108,11980937.0,82.875,2.639665,17.125,26340.0,2.849763,5886052.0,40.136129
SOM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7313284.0,50.393336,14589119.0,55.609,2.804769,44.391,637660.0,2.853684,7275835.0,46.752980
ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28883601.0,65.630562,57000451.0,34.150,1.407741,65.850,1219090.0,5.219179,28116850.0,29.150260
SSD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5451274.0,54.527406,10910759.0,80.654,0.719738,19.346,NaN,3.415765,5459485.0,42.056830
TZA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27367208.0,53.099890,54663906.0,66.947,2.995388,33.053,947300.0,2.583661,27296698.0,44.316449
UGA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20916321.0,50.759757,41162465.0,76.804,3.749875,23.196,241550.0,1.920305,20246144.0,47.319938
ZMB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8510888.0,52.503824,16853688.0,57.024,2.951583,42.976,752610.0,2.084807,8342800.0,45.411369
ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7459621.0,54.505941,14236745.0,67.763,1.460061,32.237,390760.0,2.896191,6777124.0,42.597868

## Web Scraping (Test)

In [43]:
#UNCOMMENT (!PIP INSTALL) BEFORE RUNNING THIS CODE AND THEN COMMENT BACK AGAIN TO SPEED THE PROCESS
#!pip install world_bank_data --upgrade 

import world_bank_data as wb

# It's necessary to get the indicators code, this is different from the column names. 
    # E.g: Income share held by fourth 20% is coded as: SI.DST.04TH.20
    
missingIndicators = Africa_mc[Africa_mc >= 1].index.copy()

# Created empty dataframe with the column format that the API will return
    # We just need to append in a simple loop
indicatorsCodedMissing = pd.DataFrame(columns = ['name', 'unit', 'source', 'sourceNote', 'sourceOrganization', 'topics'])

# Loop to get the missing indicators and store the in the indicatorsCodedMissing data frame
for i in list(missingIndicators):
    indicatorsCodedMissing = indicatorsCodedMissing.append(wb.search_indicators(i))

# view the first the indicator names
print(f'{indicatorsCodedMissing.index[0:3]} \n')

indicatorsCodedMissing.head()

Index(['SI.DST.05TH.20', 'SI.DST.03RD.20', 'SI.DST.02ND.20'], dtype='object')

,name,unit,source,sourceNote,sourceOrganization,topics
SI.DST.05TH.20,Income share held by highest 20%,,World Development Indicators,Percentage share of income or consumption is t...,"World Bank, Development Research Group. Data a...",Poverty
SI.DST.03RD.20,Income share held by third 20%,,World Development Indicators,Percentage share of income or consumption is t...,"World Bank, Development Research Group. Data a...",Poverty
SI.DST.02ND.20,Income share held by second 20%,,World Development Indicators,Percentage share of income or consumption is t...,"World Bank, Development Research Group. Data a...",Poverty
SI.DST.FRST.20,Income share held by lowest 20%,,World Development Indicators,Percentage share of income or consumption is t...,"World Bank, Development Research Group. Data a...","Poverty ,Aid Effectiveness"
SI.DST.04TH.20,Income share held by fourth 20%,,World Development Indicators,Percentage share of income or consumption is t...,"World Bank, Development Research Group. Data a...",Poverty

In [45]:
# Now we obtain the data for the specific countries that we need

#UNCOMMENT (!PIP INSTALL) BEFORE RUNNING THIS CODE AND THEN COMMENT BACK AGAIN TO SPEED THE PROCESS 
#!pip install wbdata

import wbdata
from datetime import datetime

# missingIndicators = AfricaheadMissingCols[AfricaheadMissingCols > 1] 

# The indicators argument of get_dataframe needs to be a dictionary with 
    # the codes (previous step) as the key and the new column names as the values (missing Indicators)
    # It will return the Data frame with all the years in the world bank 
    
keys = list(indicatorsCodedMissing.index)
values = list(missingIndicators) 

wbQueriedAfrica = wbdata.get_dataframe(indicators = dict(zip(keys,values)), country = Africa, convert_date = False)

wbQueriedAfrica.head()

               Educational attainment, at least Master's or equivalent, population 25+, total (%) (cumulative)  \
country  date
Botswana 1960                                                NaN
         1961                                                NaN
         1962                                                NaN
         1963                                                NaN
         1964                                                NaN

               Literacy rate, youth total (% of people ages 15-24)  \
country  date
Botswana 1960                                                NaN
         1961                                                NaN
         1962                                                NaN
         1963                                                NaN
         1964                                                NaN

               Educational attainment, at least Bachelor's or equivalent, population 25+, total (%) (cumulative)  \
country  date
Botswana 1960                                                NaN
         1961                                                NaN
         1962                                                NaN
         1963                                                NaN
         1964                                                NaN

               Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative)  \
country  date
Botswana 1960                                                NaN
         1961                                                NaN
         1962                                                NaN
         1963                                                NaN
         1964                                                NaN

               Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative)  \
country  date
Botswana 1960                                                NaN
         1961                                                NaN
         1962                                                NaN
         1963                                                NaN
         1964                                                NaN

               Prevalence of underweight, weight for age (% of children under 5)  \
country  date
Botswana 1960                                             9752.0
         1961                                             9870.0
         1962                                            10190.0
         1963                                            10640.0
         1964                                            11113.0

               Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative)  \
country  date
Botswana 1960                                                NaN
         1961                                                NaN
         1962                                                NaN
         1963                                                NaN
         1964                                                NaN

               Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative)  \
country  date
Botswana 1960                                             9778.0
         1961                                             9658.0
         1962                                            10148.0
         1963                                            10421.0
         1964                                            10714.0

               Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)  \
country  date
Botswana 1960                                                NaN
         1961                                                NaN
         1962                                                NaN
         1963                                                NaN
         1964                                                NaN

               Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative)  \
country  date
Botswana 1960                                             9647.0
         1961                                             9607.0
         1962                                             9561.0
         1963                                            10146.0
         1964                                            10320.0

               ...  Population, female  \
country  date  ...
Botswana 1960  ...              4861.0
         1961  ...              4714.0
         1962  ...              4587.0
         1963  ...              4440.0
         1964  ...              4490.0

               Population ages 15-64 (% of total population)  \
country  date
Botswana 1960                                            NaN
         1961                                            NaN
         1962                                            NaN
         1963                                            NaN
         1964                                            NaN

               Population, total  Rural population (% of total population)  \
country  date
Botswana 1960             4947.0                                       NaN
         1961             4829.0                                       NaN
         1962             4679.0                                       NaN
         1963             4551.0                                       NaN
         1964             4407.0                                       NaN

               Population growth (annual %)  \
country  date
Botswana 1960                        4954.0
         1961                        4913.0
         1962                        4796.0
         1963                        4646.0
         1964                        4520.0

               Urban population (% of total population)  \
country  date
Botswana 1960                                       NaN
         1961                                       NaN
         1962                                       NaN
         1963                                       NaN
         1964                                       NaN

               Surface area (sq. km)  \
country  date
Botswana 1960                 4908.0
         1961                 4914.0
         1962                 4878.0
         1963                 4764.0
         1964                 4617.0

               Population ages 65 and above (% of total population)  \
country  date
Botswana 1960                                                NaN
         1961                                                NaN
         1962                                                NaN
         1963                                                NaN
         1964                                                NaN

               Population, male  Population ages 0-14 (% of total population)
country  date
Botswana 1960            4890.0                                           NaN
         1961            4858.0                                           NaN
         1962            4871.0                                           NaN
         1963            4843.0                                           NaN
         1964            4736.0                                           NaN

[5 rows x 47 columns]

In [46]:
# Subseting  for a particular year

wbQueriedAfrica.sort_index(inplace=True)

# What is the total of missing values that there are per year 
for i in range(2010,2019,1):
    print('{} missing values out of {} for year {} '.format(wbQueriedAfrica.xs(str(i),level='date'). 
                                                            transpose().isnull().sum().sum(), # Calculates overall sum of null values
                                                            wbQueriedAfrica.shape[1] * len(wbQueriedAfrica.index.levels[0]), # Number of columns * number of countries = total possible missing values 
                                                            i) # ith year 
        )

# It seems that 2015 is the most non-missing updated info that we can obtain 

# data for 2015 is queried
wbQueriedAfrica2017 = wbQueriedAfrica.xs('2017',level='date')

# Printing the data frame to know the contents
wbQueriedAfrica2017

# saving it to excel
   
wbQueriedAfrica2017.to_excel('worldBank2017AfricaCountries.xlsx')  # This is commented so I don't overwrite by mistake the file

91 missing values out of 987 for year 2010
111 missing values out of 987 for year 2011
132 missing values out of 987 for year 2012
132 missing values out of 987 for year 2013
557 missing values out of 987 for year 2014
122 missing values out of 987 for year 2015
552 missing values out of 987 for year 2016
562 missing values out of 987 for year 2017
567 missing values out of 987 for year 2018

***
<br><br><br><br><br>
<h2>Anomaly Detection and Treatment: Outliers</h2>

In [ ]:
## New! ##
# dictionary for data types
types = {'Obs'       : str,
         'carat'     : float,
         'color'     : int,
         'clarity'   : int,
         'cut'       : int,
         'channel'   : 'category',
         'store'     : 'category',
         'price'     : int,
         'm_carat'   : int,
         'm_color'   : int,
         'm_clarity' : int,
         'm_cut'     : int}